debug: false
mqtt:
  enabled: true
  username: user
  password: "passwd"
  port: 1883
  server: "5.100.13.37"
  topicroot: camera-alerts
hisilicon:
   enabled: false
   port: 15002
ftp:
  enabled: false
  port: 21
  password: "root"
  allowFiles: true
  rootPath: "./ftp"   
