name: "AlarmServer"
description: "My first real add-on!"
version: "1.0.0"
slug: "example"
init: false
arch:
  - aarch64
  - amd64
  - armhf
  - armv7
  - i386
startup: before
ports:
  15002/tcp: 15002
  21/tcp: 21
