debug: true


hisilicon:
  enabled: true
  port: 15002



mqtt:
  enabled: true
  username: user
  password: "passwd"
  port: 1883
  server: "5.100.13.37"
  topicroot: camera-alerts

